package com.reactnativeintune

import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.WritableMap
import com.facebook.react.modules.core.DeviceEventManagerModule
import android.os.Handler
import android.os.Looper
import android.util.Log
import com.microsoft.intune.mam.client.app.MAMComponents
import com.microsoft.intune.mam.client.strict.MAMStrictMode
import com.microsoft.intune.mam.policy.MAMEnrollmentManager

/**
 * TurboModule implementation. `NativeIntuneSpec` is generated by Codegen from
 * `src/NativeIntune.ts` into this same package (`codegenConfig.android.javaPackageName`),
 * so there is nothing to import.
 *
 * Every spec parameter arrives as a [ReadableMap] because Codegen maps inline object
 * types that way on Android — unlike iOS, where they become typed C++ structs. Read keys
 * through the constants in [Keys] rather than inline strings: a typo in a key is silent.
 */
class RNIntuneModule(private val reactContext: ReactApplicationContext) :
  NativeIntuneSpec(reactContext) {

  /**
   * Events emitted before JS subscribed. A wipe notification lost during startup means
   * the reset machine never runs, so they are queued rather than dropped (SPEC §4.4).
   * The emitter is live from construction, not from the first `enroll()`.
   */
  private val pendingEvents = mutableListOf<Pair<String, WritableMap>>()
  private var listenerCount = 0

  private var config: Config? = null

  /** Held so they can be unregistered; also proves the plugin processed the app. */
  private var registrations: List<RNIntuneNotifications.Registration> = emptyList()

  /**
   * The account this process registered. Android cannot enumerate registered accounts,
   * so there is nothing to read it back from after a restart.
   */
  private var registeredAccountId: String? = null

  /** accountId -> completion, settled from the notification receiver. */
  private val pendingEnrollments = mutableMapOf<String, (WritableMap) -> Unit>()

  private val timeoutHandler = Handler(Looper.getMainLooper())

  /** Resolved configuration. `index.ts` applies every default, so nothing is optional. */
  private data class Config(
    val clientId: String,
    val tenantId: String,
    val authority: String,
    val redirectUri: String,
    val authMode: String,
    val verboseLogging: Boolean,
    val strictMode: Boolean,
    val telemetryEnabled: Boolean,
  )

  // ------------------------------------------------------------------ lifecycle

  init {
    // The callback object outlives any single React context — it is registered from
    // Application.onMAMCreate — so it is pointed at whichever module instance is live.
    RNIntuneAuthCallback.attach(this)
  }

  override fun invalidate() {
    RNIntuneAuthCallback.detach(this)
    timeoutHandler.removeCallbacksAndMessages(null)
    RNIntuneNotifications.unregister(registrations)
    registrations = emptyList()
    super.invalidate()
  }

  override fun configure(config: ReadableMap, promise: Promise) {
    if (!sdkAvailable) {
      promise.reject(
        ERR_SDK_UNAVAILABLE,
        "The Intune MAM SDK is not on the classpath. Check that vendor/android was " +
          "fetched and that the MAM Gradle plugin is applied in the app module.",
      )
      return
    }

    val incoming =
      Config(
        clientId = config.getString(Keys.CLIENT_ID).orEmpty(),
        tenantId = config.getString(Keys.TENANT_ID).orEmpty(),
        authority = config.getString(Keys.AUTHORITY).orEmpty(),
        redirectUri = config.getString(Keys.REDIRECT_URI).orEmpty(),
        authMode = config.getString(Keys.AUTH_MODE).orEmpty(),
        verboseLogging = config.getBoolean(Keys.VERBOSE_LOGGING),
        strictMode = config.getBoolean(Keys.STRICT_MODE),
        telemetryEnabled = config.getBoolean(Keys.TELEMETRY_ENABLED),
      )

    // Switching tenants requires an explicit reset: reconfiguring in place would leave
    // the previous tenant registered (SPEC §13.1).
    val active = this.config
    if (active != null && active.tenantId != incoming.tenantId) {
      promise.reject(
        ERR_RESET_REQUIRED,
        "configure() was called with a different tenantId than the active one. " +
          "Call reset() before switching tenants.",
      )
      return
    }

    // Strict Mode throws on integration bugs that would otherwise silently leave
    // corporate data unprotected. It is not meant for production, which is why the
    // public default is __DEV__ and not `true` (SPEC §6.1).
    if (incoming.strictMode) {
      runCatching { MAMStrictMode.enable() }
        .onFailure { Log.w(TAG, "MAM Strict Mode could not be enabled: ${it.message}") }
    }

    // Registered once and kept for the process lifetime: the SDK notifies unprompted,
    // including on its own enrollment retry schedule and for service-initiated wipes.
    if (registrations.isEmpty()) {
      registrations = RNIntuneNotifications.register(::emit)
      if (registrations.isEmpty()) {
        // MAMComponents returns null when the app was not processed by the MAM Gradle
        // plugin. Everything would then appear to work while nothing was protected, so
        // this is the one integration mistake worth refusing to start on.
        promise.reject(
          ERR_SDK_UNAVAILABLE,
          "The MAM notification registry is unavailable. This app was almost certainly " +
            "built without the MAM Gradle plugin applied to its app module — see the " +
            "README integration checklist. Without it the SDK is present but inert.",
        )
        return
      }
    }

    this.config = incoming

    // Unlike iOS there is no runtime override to set: these values are held here and
    // passed per-call to registerAccountForMAM (SPEC §13.1). The MAM service auth
    // callback is not registered here either — it has to be in place from
    // Application.onMAMCreate, long before this method can run, so it is the consumer's
    // wiring and we only supply the class (SPEC §6.1.2).
    promise.resolve(null)
  }

  override fun isSupported(promise: Promise) {
    promise.resolve(sdkAvailable)
  }

  override fun getBrokerStatus(promise: Promise) {
    val companyPortal = isPackageInstalled(COMPANY_PORTAL_PACKAGE)

    promise.resolve(
      Arguments.createMap().apply {
        putBoolean("brokerAvailable", companyPortal)
        putBoolean("companyPortalInstalled", companyPortal)
        // Authenticator is not a broker for MAM on Android.
        putBoolean("authenticatorInstalled", false)
        // Company Portal is mandatory here — enrollment is impossible without it.
        putBoolean("required", true)
      }
    )
  }

  override fun openBrokerInstall(promise: Promise) {
    promise.reject(ERR_NOT_CONFIGURED, "openBrokerInstall was called before configure() resolved.")
  }

  // ------------------------------------------------------------------ auth

  override fun signIn(params: ReadableMap, promise: Promise) = notConfigured("signIn", promise)

  override fun signInSilent(params: ReadableMap, promise: Promise) =
    notConfigured("signInSilent", promise)

  override fun acquireToken(params: ReadableMap, promise: Promise) =
    notConfigured("acquireToken", promise)

  override fun getAccounts(promise: Promise) = notConfigured("getAccounts", promise)

  override fun signOut(params: ReadableMap, promise: Promise) = notConfigured("signOut", promise)

  // ------------------------------------------------------------------ enrollment

  override fun enroll(params: ReadableMap, promise: Promise) {
    val config = this.config
    if (config == null) {
      notConfigured("enroll", promise)
      return
    }

    val accountId = params.getString("accountId").orEmpty()
    if (accountId.isEmpty()) {
      promise.reject(ERR_INVALID_ACCOUNT_ID, "enroll() requires an Entra object ID.")
      return
    }

    // registerAccountForMAM(upn, aadId, tenantId, authority) — parameter order verified
    // from bytecode, not documentation: the offline implementation forwards them to
    // MAMIdentityManager.insertOrUpdate(aadId, upn, tenantId, authority), which in turn
    // builds MAMIdentity(upn, aadId, authority, tenantId).
    //
    // The UPN is required and NonNull, and this module's public API deliberately takes
    // only the Entra object ID (SPEC §13.2). Nothing can supply the UPN yet: in
    // authMode 'builtin' it comes from the module's own MSAL sign-in, which is spike
    // S-3. Rejecting here with a named code beats calling the SDK with a fabricated
    // identity, which would register the wrong account.
    val upn = knownUpnFor(accountId)
    if (upn == null) {
      promise.reject(
        ERR_UPN_REQUIRED,
        "Android enrollment needs the account's UPN as well as its object ID — " +
          "MAMEnrollmentManager.registerAccountForMAM takes both, and the UPN is not " +
          "optional. It will come from the module's own MSAL sign-in (SPEC §3, spike " +
          "S-3); until then there is nothing to supply it. iOS is unaffected: " +
          "registerAndEnrollAccountId takes the object ID alone.",
      )
      return
    }

    val manager = MAMComponents.get(MAMEnrollmentManager::class.java)
    if (manager == null) {
      promise.reject(
        ERR_SDK_UNAVAILABLE,
        "MAMEnrollmentManager is unavailable — the MAM Gradle plugin is almost " +
          "certainly not applied to this app module.",
      )
      return
    }

    // Held against the account ID and settled from the notification receiver. The call
    // below returns immediately and says nothing about the outcome (SPEC §12.5).
    synchronized(pendingEnrollments) {
      val existing = pendingEnrollments[accountId]
      pendingEnrollments[accountId] = { result ->
        existing?.invoke(result)
        promise.resolve(result)
      }
    }

    scheduleEnrollTimeout(accountId)

    registeredAccountId = accountId
    manager.registerAccountForMAM(upn, accountId, config.tenantId, config.authority)
  }

  /**
   * The UPN for an object ID, once something knows it.
   *
   * Always null today. It becomes the MSAL account lookup in the auth slice; keeping the
   * seam here means `enroll` does not change shape when that lands.
   */
  private fun knownUpnFor(@Suppress("UNUSED_PARAMETER") accountId: String): String? = null

  private fun scheduleEnrollTimeout(accountId: String) {
    timeoutHandler.postDelayed({
      // Truthful rather than convenient: the SDK has not failed, it has not answered.
      // It keeps retrying on its own schedule and the result still arrives as an event.
      settleEnrollment(
        accountId,
        Arguments.createMap().apply {
          putString("status", "pending")
          putString("accountId", accountId)
          putString("nativeCode", "RNIntuneTimeout")
          putString(
            "nativeMessage",
            "The SDK did not report a result within the timeout. Enrollment continues " +
              "in the background; watch onEnrollmentResult.",
          )
          putBoolean("restartRequired", false)
        },
      )
    }, ENROLL_TIMEOUT_MS)
  }

  private fun settleEnrollment(accountId: String, result: WritableMap) {
    val completion = synchronized(pendingEnrollments) { pendingEnrollments.remove(accountId) }
    completion?.invoke(result)
  }

  override fun getState(promise: Promise) {
    // Deliberately never rejects: reporting `configured: false` is what makes this the
    // reconciliation primitive (SPEC §13.2).
    //
    // Android has no "list registered accounts" API — getRegisteredAccountStatus takes
    // an account ID and answers for that one. So the registered set is whatever this
    // process registered, and after a restart it is empty until the app reconciles.
    // That asymmetry with iOS (which has registeredAccountIds) is why the host app
    // compares against its own backend rather than trusting this list alone.
    val registered = registeredAccountId
    val status = registered?.let { readStatus(it) }

    promise.resolve(
      Arguments.createMap().apply {
        putBoolean("configured", config != null)
        putString("configuredTenantId", config?.tenantId)
        putArray(
          "registeredAccountIds",
          Arguments.createArray().apply { registered?.let { pushString(it) } },
        )
        putString(
          "enrolledAccountId",
          if (RNIntuneNotifications.unifiedStatus(status) == "succeeded") registered else null,
        )
        putString("status", status?.let { RNIntuneNotifications.unifiedStatus(it) })
        // Written by the reset journal, which is SPEC §7 and not yet implemented.
        putNull("pendingReset")
      }
    )
  }

  override fun reset(params: ReadableMap, promise: Promise) = notConfigured("reset", promise)

  // ------------------------------------------------------------------ policy

  override fun getPolicy(promise: Promise) = notConfigured("getPolicy", promise)

  override fun getDiagnostics(promise: Promise) {
    // Account IDs may appear here but must never be logged or persisted (CLAUDE.md
    // rule 3). Nothing below is a token or a UPN.
    promise.resolve(
      Arguments.createMap().apply {
        putString("platform", "android")
        putString("sdkLinked", sdkAvailable.toString())
        putString("configured", (config != null).toString())
        putString("configuredTenantId", config?.tenantId.orEmpty())
        putString("authMode", config?.authMode.orEmpty())
        putString("companyPortalInstalled", isPackageInstalled(COMPANY_PORTAL_PACKAGE).toString())
        putString("strictMode", (config?.strictMode ?: false).toString())
        putString("notificationReceiversRegistered", registrations.size.toString())
        if (sdkAvailable) {
          // MAMComponents answers these without an enrolled account, and neither is a
          // token, a UPN or an account ID (CLAUDE.md rule 3).
          putString(
            "managedApp",
            runCatching { MAMComponents.isManagedApp(reactContext).toString() }
              .getOrDefault("unknown"),
          )
          putString(
            "wipeInProgress",
            runCatching { MAMComponents.isWipeInProgress(reactContext).toString() }
              .getOrDefault("unknown"),
          )
        }
      }
    )
  }

  // ------------------------------------------------------------------ token provider

  /**
   * Not public API — `setTokenProvider` in `index.ts` wraps these. The MAM service token
   * never crosses back out to JS and is never logged (CLAUDE.md rule 9).
   *
   * Wiring lands with the auth callback (SPEC §13.4): the SDK asks on a background
   * thread, including on its own retry schedule with no JS call in flight, so the
   * request has to be correlated by `requestId` rather than awaited inline.
   */
  override fun resolveToken(params: ReadableMap) {
    val requestId = params.getString("requestId") ?: return
    RNIntuneAuthCallback.resolve(requestId, params.getString("token").orEmpty())
  }

  override fun rejectToken(params: ReadableMap) {
    val requestId = params.getString("requestId") ?: return
    RNIntuneAuthCallback.reject(requestId, params.getString("reason").orEmpty())
  }

  // ------------------------------------------------------------------ events

  override fun addListener(eventName: String) {
    listenerCount += 1
    if (listenerCount == 1) flushPendingEvents()
  }

  override fun removeListeners(count: Double) {
    listenerCount = (listenerCount - count.toInt()).coerceAtLeast(0)
  }

  /** Called by the auth callback from the SDK's background thread. */
  internal fun emitTokenRequest(
    requestId: String,
    resourceId: String,
    accountId: String,
    tenantId: String,
    authority: String,
  ) {
    emit(
      "tokenRequest",
      Arguments.createMap().apply {
        putString("requestId", requestId)
        putString("resourceId", resourceId)
        putString("accountId", accountId)
        putString("tenantId", tenantId)
        putString("authority", authority)
      },
    )
  }

  /** Emits now if JS is listening, queues otherwise. */
  internal fun emit(event: String, payload: WritableMap) {
    // Settle first, publish second. The same notification serves a caller waiting on
    // enroll() and every subscriber — including for the SDK's own background retries,
    // which have no caller at all (SPEC §13.5).
    if (event == "enrollmentResult" || event == "unenrollmentResult") {
      payload.getString("accountId")?.let { settleEnrollment(it, payload.copy()) }
    }

    if (listenerCount == 0) {
      pendingEvents += event to payload
      return
    }
    sendEvent(event, payload)
  }

  private fun flushPendingEvents() {
    val queued = pendingEvents.toList()
    pendingEvents.clear()
    queued.forEach { (event, payload) -> sendEvent(event, payload) }
  }

  private fun sendEvent(event: String, payload: WritableMap) {
    reactContext
      .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
      .emit(event, payload)
  }

  // ------------------------------------------------------------------ helpers

  /**
   * [verify] The single-argument `getRegisteredAccountStatus` is deprecated in favour of
   * a two-argument overload, but the AAR's class files carry no parameter *names* — only
   * `@NonNull` on both — so what the second argument means cannot be established from
   * the binary. By symmetry with `registerAccountForMAM(upn, aadId, tenantId)` it is
   * probably `(upn, aadId)`, but both overloads compile identically under either
   * reading, which is exactly the kind of guess that costs a build cycle and sometimes
   * passes silently (CLAUDE.md rule 1).
   *
   * So the deprecated overload stays until the enrollment slice, where MSAL supplies the
   * UPN and the object ID together and the right call can be confirmed against a real
   * tenant. Deprecated here means "superseded", not "removed".
   */
  @Suppress("DEPRECATION")
  private fun readStatus(accountId: String): MAMEnrollmentManager.Result? =
    runCatching {
      MAMComponents.get(MAMEnrollmentManager::class.java)?.getRegisteredAccountStatus(accountId)
    }
      .getOrNull()

  /**
   * True when the MAM SDK is on the classpath. Resolved by name so this file needs no
   * SDK import to answer it, and so a misbuilt app degrades instead of crashing.
   */
  private val sdkAvailable: Boolean by lazy {
    runCatching { Class.forName("com.microsoft.intune.mam.policy.MAMEnrollmentManager") }
      .isSuccess
  }

  /**
   * Requires a `<queries>` entry for the package in the consumer's manifest on Android
   * 11+. Without it this returns false even when Company Portal is installed — the same
   * omission that makes MSAL fall back to a browser and lose the broker (SPEC §6.2).
   */
  private fun isPackageInstalled(packageName: String): Boolean =
    runCatching { reactContext.packageManager.getPackageInfo(packageName, 0) }.isSuccess

  private fun notConfigured(method: String, promise: Promise) {
    promise.reject(ERR_NOT_CONFIGURED, "$method was called before configure() resolved.")
  }

  /** Spec field names, kept in one place because a typo'd `ReadableMap` key is silent. */
  private object Keys {
    const val CLIENT_ID = "clientId"
    const val TENANT_ID = "tenantId"
    const val AUTHORITY = "authority"
    const val REDIRECT_URI = "redirectUri"
    const val AUTH_MODE = "authMode"
    const val VERBOSE_LOGGING = "verboseLogging"
    const val STRICT_MODE = "strictMode"
    const val TELEMETRY_ENABLED = "telemetryEnabled"
  }

  companion object {
    /** Resolves to "RNIntune" — the name in TurboModuleRegistry.getEnforcing (SPEC §2.2). */
    const val NAME = NativeIntuneSpec.NAME

    private const val TAG = "RNIntune"

    private const val COMPANY_PORTAL_PACKAGE = "com.microsoft.windowsintune.companyportal"

    // Stable rejection codes (SPEC §13.6). Never surface a raw platform error to JS.
    private const val ERR_NOT_CONFIGURED = "E_NOT_CONFIGURED"
    private const val ERR_RESET_REQUIRED = "E_RESET_REQUIRED"
    private const val ERR_SDK_UNAVAILABLE = "E_SDK_UNAVAILABLE"
    private const val ERR_INVALID_ACCOUNT_ID = "E_INVALID_ACCOUNT_ID"
    private const val ERR_UPN_REQUIRED = "E_UPN_REQUIRED"

    /**
     * Generous on purpose: enrollment involves a token acquisition and a service round
     * trip, and returning early would report a failure the SDK has not reached.
     */
    private const val ENROLL_TIMEOUT_MS = 90_000L
  }
}
