package com.reactnativeintune

import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.WritableMap
import com.facebook.react.modules.core.DeviceEventManagerModule

/**
 * TurboModule implementation. `NativeIntuneSpec` is generated by Codegen from
 * `src/NativeIntune.ts` into this same package (`codegenConfig.android.javaPackageName`),
 * so there is nothing to import.
 *
 * Every spec parameter arrives as a [ReadableMap] because Codegen maps inline object
 * types that way on Android — unlike iOS, where they become typed C++ structs. Read keys
 * through the constants in [Keys] rather than inline strings: a typo in a key is silent.
 */
class RNIntuneModule(private val reactContext: ReactApplicationContext) :
  NativeIntuneSpec(reactContext) {

  /**
   * Events emitted before JS subscribed. A wipe notification lost during startup means
   * the reset machine never runs, so they are queued rather than dropped (SPEC §4.4).
   * The emitter is live from construction, not from the first `enroll()`.
   */
  private val pendingEvents = mutableListOf<Pair<String, WritableMap>>()
  private var listenerCount = 0

  private var config: Config? = null

  /** Resolved configuration. `index.ts` applies every default, so nothing is optional. */
  private data class Config(
    val clientId: String,
    val tenantId: String,
    val authority: String,
    val redirectUri: String,
    val authMode: String,
    val verboseLogging: Boolean,
    val strictMode: Boolean,
    val telemetryEnabled: Boolean,
  )

  // ------------------------------------------------------------------ lifecycle

  override fun configure(config: ReadableMap, promise: Promise) {
    if (!sdkAvailable) {
      promise.reject(
        ERR_SDK_UNAVAILABLE,
        "The Intune MAM SDK is not on the classpath. Check that vendor/android was " +
          "fetched and that the MAM Gradle plugin is applied in the app module.",
      )
      return
    }

    val incoming =
      Config(
        clientId = config.getString(Keys.CLIENT_ID).orEmpty(),
        tenantId = config.getString(Keys.TENANT_ID).orEmpty(),
        authority = config.getString(Keys.AUTHORITY).orEmpty(),
        redirectUri = config.getString(Keys.REDIRECT_URI).orEmpty(),
        authMode = config.getString(Keys.AUTH_MODE).orEmpty(),
        verboseLogging = config.getBoolean(Keys.VERBOSE_LOGGING),
        strictMode = config.getBoolean(Keys.STRICT_MODE),
        telemetryEnabled = config.getBoolean(Keys.TELEMETRY_ENABLED),
      )

    // Switching tenants requires an explicit reset: reconfiguring in place would leave
    // the previous tenant registered (SPEC §13.1).
    val active = this.config
    if (active != null && active.tenantId != incoming.tenantId) {
      promise.reject(
        ERR_RESET_REQUIRED,
        "configure() was called with a different tenantId than the active one. " +
          "Call reset() before switching tenants.",
      )
      return
    }

    this.config = incoming

    // Unlike iOS, Android has no runtime override to set: the values are held here and
    // passed per-call to registerAccountForMAM (SPEC §13.1). Registering the auth
    // callback and the notification receivers lands in the next slice — and the callback
    // has to be registered from Application.onMAMCreate, earlier than this method can
    // ever run, so it is the consumer's wiring and not ours to do here (SPEC §6.1.1).
    promise.resolve(null)
  }

  override fun isSupported(promise: Promise) {
    promise.resolve(sdkAvailable)
  }

  override fun getBrokerStatus(promise: Promise) {
    val companyPortal = isPackageInstalled(COMPANY_PORTAL_PACKAGE)

    promise.resolve(
      Arguments.createMap().apply {
        putBoolean("brokerAvailable", companyPortal)
        putBoolean("companyPortalInstalled", companyPortal)
        // Authenticator is not a broker for MAM on Android.
        putBoolean("authenticatorInstalled", false)
        // Company Portal is mandatory here — enrollment is impossible without it.
        putBoolean("required", true)
      }
    )
  }

  override fun openBrokerInstall(promise: Promise) {
    promise.reject(ERR_NOT_CONFIGURED, "openBrokerInstall was called before configure() resolved.")
  }

  // ------------------------------------------------------------------ auth

  override fun signIn(params: ReadableMap, promise: Promise) = notConfigured("signIn", promise)

  override fun signInSilent(params: ReadableMap, promise: Promise) =
    notConfigured("signInSilent", promise)

  override fun acquireToken(params: ReadableMap, promise: Promise) =
    notConfigured("acquireToken", promise)

  override fun getAccounts(promise: Promise) = notConfigured("getAccounts", promise)

  override fun signOut(params: ReadableMap, promise: Promise) = notConfigured("signOut", promise)

  // ------------------------------------------------------------------ enrollment

  override fun enroll(params: ReadableMap, promise: Promise) = notConfigured("enroll", promise)

  override fun getState(promise: Promise) {
    // Deliberately never rejects: reporting `configured: false` is what makes this the
    // reconciliation primitive (SPEC §13.2).
    promise.resolve(
      Arguments.createMap().apply {
        putBoolean("configured", config != null)
        putString("configuredTenantId", config?.tenantId)
        putArray("registeredAccountIds", Arguments.createArray())
        putNull("enrolledAccountId")
        putNull("status")
        putNull("pendingReset")
      }
    )
  }

  override fun reset(params: ReadableMap, promise: Promise) = notConfigured("reset", promise)

  // ------------------------------------------------------------------ policy

  override fun getPolicy(promise: Promise) = notConfigured("getPolicy", promise)

  override fun getDiagnostics(promise: Promise) {
    // Account IDs may appear here but must never be logged or persisted (CLAUDE.md
    // rule 3). Nothing below is a token or a UPN.
    promise.resolve(
      Arguments.createMap().apply {
        putString("platform", "android")
        putString("sdkLinked", sdkAvailable.toString())
        putString("configured", (config != null).toString())
        putString("configuredTenantId", config?.tenantId.orEmpty())
        putString("authMode", config?.authMode.orEmpty())
        putString("companyPortalInstalled", isPackageInstalled(COMPANY_PORTAL_PACKAGE).toString())
      }
    )
  }

  // ------------------------------------------------------------------ token provider

  /**
   * Not public API — `setTokenProvider` in `index.ts` wraps these. The MAM service token
   * never crosses back out to JS and is never logged (CLAUDE.md rule 9).
   *
   * Wiring lands with the auth callback (SPEC §13.4): the SDK asks on a background
   * thread, including on its own retry schedule with no JS call in flight, so the
   * request has to be correlated by `requestId` rather than awaited inline.
   */
  override fun resolveToken(params: ReadableMap) = Unit

  override fun rejectToken(params: ReadableMap) = Unit

  // ------------------------------------------------------------------ events

  override fun addListener(eventName: String) {
    listenerCount += 1
    if (listenerCount == 1) flushPendingEvents()
  }

  override fun removeListeners(count: Double) {
    listenerCount = (listenerCount - count.toInt()).coerceAtLeast(0)
  }

  /** Emits now if JS is listening, queues otherwise. */
  @Suppress("unused") // used by the notification receivers in the next slice
  internal fun emit(event: String, payload: WritableMap) {
    if (listenerCount == 0) {
      pendingEvents += event to payload
      return
    }
    sendEvent(event, payload)
  }

  private fun flushPendingEvents() {
    val queued = pendingEvents.toList()
    pendingEvents.clear()
    queued.forEach { (event, payload) -> sendEvent(event, payload) }
  }

  private fun sendEvent(event: String, payload: WritableMap) {
    reactContext
      .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
      .emit(event, payload)
  }

  // ------------------------------------------------------------------ helpers

  /**
   * True when the MAM SDK is on the classpath. Resolved by name so this file needs no
   * SDK import to answer it, and so a misbuilt app degrades instead of crashing.
   */
  private val sdkAvailable: Boolean by lazy {
    runCatching { Class.forName("com.microsoft.intune.mam.policy.MAMEnrollmentManager") }
      .isSuccess
  }

  /**
   * Requires a `<queries>` entry for the package in the consumer's manifest on Android
   * 11+. Without it this returns false even when Company Portal is installed — the same
   * omission that makes MSAL fall back to a browser and lose the broker (SPEC §6.2).
   */
  private fun isPackageInstalled(packageName: String): Boolean =
    runCatching { reactContext.packageManager.getPackageInfo(packageName, 0) }.isSuccess

  private fun notConfigured(method: String, promise: Promise) {
    promise.reject(ERR_NOT_CONFIGURED, "$method was called before configure() resolved.")
  }

  /** Spec field names, kept in one place because a typo'd `ReadableMap` key is silent. */
  private object Keys {
    const val CLIENT_ID = "clientId"
    const val TENANT_ID = "tenantId"
    const val AUTHORITY = "authority"
    const val REDIRECT_URI = "redirectUri"
    const val AUTH_MODE = "authMode"
    const val VERBOSE_LOGGING = "verboseLogging"
    const val STRICT_MODE = "strictMode"
    const val TELEMETRY_ENABLED = "telemetryEnabled"
  }

  companion object {
    /** Resolves to "RNIntune" — the name in TurboModuleRegistry.getEnforcing (SPEC §2.2). */
    const val NAME = NativeIntuneSpec.NAME

    private const val COMPANY_PORTAL_PACKAGE = "com.microsoft.windowsintune.companyportal"

    // Stable rejection codes (SPEC §13.6). Never surface a raw platform error to JS.
    private const val ERR_NOT_CONFIGURED = "E_NOT_CONFIGURED"
    private const val ERR_RESET_REQUIRED = "E_RESET_REQUIRED"
    private const val ERR_SDK_UNAVAILABLE = "E_SDK_UNAVAILABLE"
  }
}
