import { useCallback, useEffect, useState } from 'react';
import {
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import Intune, {
  type BrokerStatus,
  type Diagnostics,
  type IntuneState,
} from 'react-native-intune';

/**
 * Live test screen for the real tenant.
 *
 * These are the values from the `react-native-intune-test` app registration. They are
 * identifiers, not secrets — the client ID is public by design and the tenant ID appears
 * in sign-in URLs.
 */
const TENANT_ID = '00000000-0000-0000-0000-000000000000';
const CLIENT_ID = '00000000-0000-0000-0000-000000000000';

/**
 * Generated by Entra from the bundle ID and, on Android, the signature hash. Both are
 * registered under the app registration's platform entries.
 */
const REDIRECT_URI = Platform.select({
  ios: 'msauth.intune.example://auth',
  default: 'msauth://intune.example/Xo8WBi6jzSxKDVR4drqm84yr9iU%3D',
});

export default function App() {
  const [supported, setSupported] = useState('…');
  const [broker, setBroker] = useState<BrokerStatus | null>(null);
  const [state, setState] = useState<IntuneState | null>(null);
  const [diagnostics, setDiagnostics] = useState<Diagnostics | null>(null);
  const [configureResult, setConfigureResult] = useState('not called');
  const [enrollResult, setEnrollResult] = useState('not called');
  const [tokenAsked, setTokenAsked] = useState('never');
  const [upn, setUpn] = useState('intune-ok@<tenant>.onmicrosoft.com');

  const refresh = useCallback(async () => {
    try {
      setState(await Intune.getState());
    } catch (e) {
      setConfigureResult(`getState: ${describe(e)}`);
    }
    try {
      setDiagnostics(await Intune.getDiagnostics());
    } catch {
      setDiagnostics(null);
    }
  }, []);

  const runConfigure = useCallback(async () => {
    setConfigureResult('…');
    try {
      await Intune.configure({
        clientId: CLIENT_ID,
        tenantId: TENANT_ID,
        authority: `https://login.microsoftonline.com/${TENANT_ID}`,
        redirectUri: REDIRECT_URI,
        verboseLogging: true,
      });
      setConfigureResult('resolved');
    } catch (e) {
      setConfigureResult(describe(e));
    }
    await refresh();
  }, [refresh]);

  /** Must reject with E_RESET_REQUIRED — silently reconfiguring would leave the old
   * tenant enrolled. */
  const runTenantSwitch = useCallback(async () => {
    setConfigureResult('…');
    try {
      await Intune.configure({
        clientId: CLIENT_ID,
        tenantId: '00000000-0000-0000-0000-000000000002',
        authority: 'https://login.microsoftonline.com/other',
        redirectUri: REDIRECT_URI,
      });
      setConfigureResult('resolved (expected E_RESET_REQUIRED!)');
    } catch (e) {
      setConfigureResult(describe(e));
    }
    await refresh();
  }, [refresh]);

  /**
   * The SDK runs the sign-in itself and shows its own screen, so this reaches a real
   * enrollment without the module's MSAL layer (spike S-3) existing yet. iOS only.
   */
  const runEnrollInteractive = useCallback(async () => {
    setEnrollResult('signing in…');
    try {
      const r = await Intune.enrollInteractive({ upn });
      // Resolves for every outcome — a non-success status is data, not an exception.
      setEnrollResult(`${r.status} (${r.nativeCode})`);
    } catch (e) {
      setEnrollResult(describe(e));
    }
    await refresh();
  }, [refresh, upn]);

  const runReset = useCallback(async () => {
    setEnrollResult('resetting…');
    try {
      await Intune.reset({ wipe: true, reason: 'support_reset' });
      setEnrollResult('reset resolved');
    } catch (e) {
      setEnrollResult(`reset: ${describe(e)}`);
    }
    await refresh();
  }, [refresh]);

  useEffect(() => {
    // Declines every request, on purpose. There is no tenant and no MSAL yet, so the
    // point is to prove the round trip runs at all: SDK asks -> native emits
    // tokenRequest -> this provider answers -> native tells the SDK (SPEC §13.4).
    // Proves the journal is what drives the sequence: the handler runs after the
    // native unregister, not before, and a throw here leaves the journal open.
    Intune.setResetHandler(({ reason }) => {
      console.log('resetHandler', reason);
    });

    Intune.setTokenProvider((request) => {
      setTokenAsked(request.resourceId || '(no resource)');
      return null;
    });

    // Subscribed before anything else is called: a service-initiated wipe can arrive
    // with no prior app call at all (SPEC §4.4).
    const subs = [
      Intune.onWipeRequested(({ accountId }) =>
        console.log('wipeRequested', accountId)
      ),
      Intune.onEnrollmentResult((r) =>
        console.log('enrollmentResult', r.status)
      ),
      Intune.onPolicyChanged(() => console.log('policyChanged')),
      Intune.onRestartRequired(({ reason }) =>
        console.log('restartRequired', reason)
      ),
    ];

    const load = async () => {
      try {
        setSupported(String(await Intune.isSupported()));
      } catch (e) {
        setSupported(describe(e));
      }
      try {
        setBroker(await Intune.getBrokerStatus());
      } catch {
        setBroker(null);
      }
      await refresh();
    };

    load().catch(() => {});

    return () => {
      subs.forEach((s) => s.remove());
      Intune.setTokenProvider(null);
      Intune.setResetHandler(null);
    };
  }, [refresh]);

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.heading}>react-native-intune</Text>

      <Row label="isSupported" value={supported} />

      <Text style={styles.section}>getBrokerStatus</Text>
      {broker === null ? (
        <Row label="" value="…" />
      ) : (
        <>
          <Row label="brokerAvailable" value={String(broker.brokerAvailable)} />
          <Row
            label="companyPortal"
            value={String(broker.companyPortalInstalled)}
          />
          <Row
            label="authenticator"
            value={String(broker.authenticatorInstalled)}
          />
          <Row label="required" value={String(broker.required)} />
        </>
      )}

      <Text style={styles.section}>configure</Text>
      <Row label="result" value={configureResult} />
      <View style={styles.buttons}>
        <Button label="configure" onPress={runConfigure} />
        <Button label="switch tenant" onPress={runTenantSwitch} />
      </View>

      <Text style={styles.section}>enroll</Text>
      <TextInput
        style={styles.input}
        value={upn}
        onChangeText={setUpn}
        autoCapitalize="none"
        autoCorrect={false}
        keyboardType="email-address"
        placeholder="UPN to sign in as"
      />
      <Row label="result" value={enrollResult} />
      <Row label="token asked for" value={tokenAsked} />
      <View style={styles.buttons}>
        <Button label="sign in + enroll" onPress={runEnrollInteractive} />
        <Button label="reset" onPress={runReset} />
      </View>

      <Text style={styles.section}>getState</Text>
      {state !== null && (
        <>
          <Row label="configured" value={String(state.configured)} />
          <Row label="tenantId" value={state.configuredTenantId ?? '—'} />
          <Row label="enrolled" value={state.enrolledAccountId ?? '—'} />
          <Row label="status" value={state.status ?? '—'} />
          <Row label="pendingReset" value={state.pendingReset ?? '—'} />
        </>
      )}

      <Text style={styles.section}>getDiagnostics</Text>
      {diagnostics === null ? (
        <Row label="" value="—" />
      ) : (
        Object.entries(diagnostics).map(([k, v]) => (
          <Row key={k} label={k} value={v === '' ? '—' : v} />
        ))
      )}
    </ScrollView>
  );
}

function describe(e: unknown): string {
  if (typeof e === 'object' && e !== null && 'code' in e) {
    return String((e as { code: unknown }).code);
  }
  return e instanceof Error ? e.message : String(e);
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}

function Button({ label, onPress }: { label: string; onPress: () => void }) {
  return (
    <Pressable style={styles.button} onPress={onPress}>
      <Text style={styles.buttonLabel}>{label}</Text>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 24,
    paddingTop: 64,
    paddingBottom: 48,
    gap: 4,
  },
  heading: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 16,
  },
  section: {
    marginTop: 20,
    marginBottom: 4,
    fontWeight: '600',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  label: {
    color: '#666',
  },
  value: {
    flexShrink: 1,
    textAlign: 'right',
  },
  input: {
    borderWidth: 1,
    borderColor: '#c7c7cc',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    fontSize: 15,
  },
  buttons: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  button: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: '#e5e5ea',
  },
  buttonLabel: {
    fontWeight: '600',
  },
});
